// Generated by CoffeeScript 1.8.0
(function() {
  var markup, yaml, _;

  _ = require('underscore');

  _.str = require('underscore.string');

  yaml = require('./yaml');

  markup = require('./markup');

  module.exports = function(raw, options) {
    var conversionOptions, convert, docs;
    if (options == null) {
      options = {};
    }
    if (options.fussy) {
      docs = yaml.safeLoadMixed(raw);
    } else {
      docs = yaml.safeLoadAll(raw);
    }
    if (options.convert || options.convertAll) {
      conversionOptions = {
        format: options.format,
        recursive: options.convertAll
      };
      convert = _.partial(markup.object, _, conversionOptions);
      docs = _.map(docs, convert);
    }
    if (yaml.isMultidoc(raw)) {
      return docs;
    } else {
      return docs[0];
    }
  };

}).call(this);
